const GALLERY_ITEMS = [
    { name: 'Ankara maternity top', price: 365, image: 'images/shared/ankara-maternity-top.jpeg', category: 'Shared' },
    { name: 'Fashion look 1', price: 245, image: 'images/shared/fashion-look-1.jpeg', category: 'Shared' },
    { name: 'Fashion look 2', price: 255, image: 'images/shared/fashion-look-2.jpeg', category: 'Shared' },
    { name: 'African dress collection', price: 400, image: 'images/shared/african-dress-collection.jpeg', category: 'Shared' },
    { name: 'Kids shoes', price: 240, image: 'images/shared/kids-shoes.jpeg', category: 'Shared' },
    { name: 'Vibrant fashion portrait', price: 470, image: 'images/shared/fashion-portrait-vibrant.jpeg', category: 'Shared' },
    { name: 'Fashion look 3', price: 260, image: 'images/shared/fashion-look-3.jpeg', category: 'Shared' },
    { name: 'Fashion look 4', price: 255, image: 'images/shared/fashion-look-4.jpeg', category: 'Shared' },
    { name: 'Dashiki set', price: 350, image: 'images/shared/dashiki-set.jpeg', category: 'Shared' },
    { name: 'Dashiki shirt', price: 645, image: 'images/shared/dashiki-shirt.jpeg', category: 'Shared' },
    { name: 'African print pant suit', price: 330, image: 'images/shared/african-print-pant-suit.jpeg', category: 'Shared' },
    { name: 'Cultural event outfit', price: 330, image: 'images/shared/cultural-event-outfit.jpeg', category: 'Shared' },
    { name: 'Tribal shirt', price: 450, image: 'images/shared/tribal-shirt.jpeg', category: 'Shared' },
    { name: 'Senator suit', price: 400, image: 'images/shared/senator-suit.jpeg', category: 'Shared' },
    { name: 'Fashion image', price: 310, image: 'images/shared/fashion-image.jpeg', category: 'Shared' },
    { name: 'Usher following Jojo', price: 335, image: 'images/shared/usher-following-jojo.jpeg', category: 'Shared' },
    { name: 'Maroon hoodie', price: 305, image: 'images/shared/maroon-hoodie.jpeg', category: 'Shared' },
    { name: 'Queens of the continent', price: 330, image: 'images/shared/queens-of-the-continent.jpeg', category: 'Shared' },
    { name: 'Patchwork tribal print', price: 330, image: 'images/shared/patchwork-tribal-print.jpeg', category: 'Shared' },
    { name: 'Dashiki wedding outfit', price: 640, image: 'images/shared/dashiki-wedding-outfit.jpeg', category: 'Shared' },
    { name: 'Fluid fashion look', price: 330, image: 'images/shared/fluid-fashion-look.jpeg', category: 'Shared' },
    { name: 'Vintage print shirt', price: 350, image: 'images/shared/vintage-print-shirt.jpeg', category: 'Shared' },
    { name: 'Off shoulder top', price: 335, image: 'images/shared/off-shoulder-top.jpeg', category: 'Shared' },
    { name: 'Child fashion', price: 215, image: 'images/shared/child.jpeg', category: 'Shared' },
    { name: 'Colorful fashion piece', price: 265, image: 'images/shared/colorful-fashion-piece.jpeg', category: 'Shared' },
    { name: 'Elegant fashion look 2', price: 265, image: 'images/shared/elegant-fashion-look-2.jpeg', category: 'Shared' },
    { name: 'Elegant fashion look', price: 260, image: 'images/shared/female.jpg', category: 'Shared' },
    { name: 'Studio fashion portrait', price: 255, image: 'images/shared/fashion-portrait-studio.jpeg', category: 'Shared' },
    { name: 'Elegant fashion portrait', price: 255, image: 'images/shared/fashion-portrait-elegant.jpeg', category: 'Shared' },
    { name: 'Glamour fashion portrait', price: 255, image: 'images/shared/fashion-portrait-glamour.jpeg', category: 'Shared' },
    { name: 'Editorial fashion portrait', price: 245, image: 'images/shared/fashion-portrait-editorial.jpeg', category: 'Shared' },
    { name: 'Plus size elegant maxi dress', price: 285, image: 'images/shared/plus-size-elegant-maxi-dress.jpeg', category: 'Shared' },
    { name: 'Premium fashion piece', price: 260, image: 'images/shared/premium-fashion-piece.jpeg', category: 'Shared' },
    { name: 'Sleeveless one shoulder top', price: 280, image: 'images/shared/sleeveless-one-shoulder-top.jpeg', category: 'Shared' },
    { name: 'Stylish casual shirt', price: 260, image: 'images/shared/stylish-casual-shirt.jpeg', category: 'Shared' },
    { name: 'Unisex fashion collection', price: 275, image: 'images/shared/unisex-fashion-collection.jpeg', category: 'Shared' },
    { name: 'African style shirt', price: 255, image: 'images/male/african-style-shirt.jpeg', category: 'Male' },
    { name: 'Classic mens shoes', price: 255, image: 'images/male/classic-mens-shoes.jpeg', category: 'Male' },
    { name: 'Maroon hoodie', price: 240, image: 'images/male/maroon-hoodie.jpeg', category: 'Male' },
    { name: 'Wedding indo western set', price: 270, image: 'images/male/wedding-indo-western-set.jpeg', category: 'Male' },
    { name: 'Ankara fashion top 2', price: 260, image: 'images/female/ankara-fashion-top-2.jpeg', category: 'Female' },
    { name: 'Ankara fashion top', price: 255, image: 'images/female/ankara-fashion-top.jpeg', category: 'Female' },
    { name: 'Butterfly sleeve dress', price: 265, image: 'images/female/butterfly-sleeve-dress.jpeg', category: 'Female' },
    { name: 'Elegant evening dress', price: 260, image: 'images/female/elegant-evening-dress.jpeg', category: 'Female' },
    { name: 'Graphic tee', price: 230, image: 'images/female/graphic-tee.jpeg', category: 'Female' },
    { name: 'Modern dress set', price: 245, image: 'images/female/modern-dress-set.jpeg', category: 'Female' },
    { name: 'Winter fashion look', price: 255, image: 'images/female/winter-fashion-look.jpeg', category: 'Female' },
];
